package com.back.backend.domain.followup.model;

public enum CandidateQuestionType {
    PROJECT_RESULT_DETAIL,
    PROJECT_RESULT_METRIC,
    PROJECT_APPROACH_REASON,
    PROJECT_SCOPE_NARROW,
    PROJECT_CORE_CLARIFY,

    PROBLEM_CAUSE_DETAIL,
    PROBLEM_VERIFICATION_DETAIL,
    PROBLEM_PREVENTION_DETAIL,
    PROBLEM_CORE_CLARIFY,

    TECH_ALTERNATIVE_COMPARE,
    TECH_TRADEOFF_DETAIL,
    TECH_EFFECT_AFTER_ADOPTION,
    TECH_CORE_CLARIFY,

    COLLAB_ISSUE_DETAIL,
    COLLAB_AGREEMENT_CRITERIA,
    COLLAB_DECISION_REASON,
    COLLAB_RESULT_IMPACT,
    COLLAB_CORE_CLARIFY
}
