insert into knowledge_tags (name, category) values
    ('backend',          'domain'),
    ('cs',               'domain'),
    ('interview',        'domain'),
    ('system-design',    'domain'),
    ('c',                'language'),
    ('java',             'language'),
    ('javascript',       'language'),
    ('python',           'language'),
    ('sql',              'language'),
    ('algorithm',        'topic'),
    ('behavioral',       'topic'),
    ('data-structure',   'topic'),
    ('database',         'topic'),
    ('design-pattern',   'topic'),
    ('docker',           'topic'),
    ('functional',       'topic'),
    ('git',              'topic'),
    ('network',          'topic'),
    ('oop',              'topic'),
    ('os',               'topic'),
    ('security',         'topic'),
    ('spring',           'topic'),
    ('testing',          'topic')
on conflict (name) do nothing;
