-- 문제은행식 면접 연습 테이블
create table practice_sessions (
    id                bigint generated by default as identity primary key,
    user_id           bigint       not null references users (id) on delete cascade,
    knowledge_item_id bigint       not null references knowledge_items (id),
    question_type     varchar(20)  not null,
    status            varchar(20)  not null default 'in_progress',
    answer_text       text,
    score             integer,
    feedback          text,
    model_answer      text,
    evaluated_at      timestamptz,
    created_at        timestamptz  not null default current_timestamp,
    updated_at        timestamptz  not null default current_timestamp,
    constraint chk_practice_sessions_question_type check (question_type in ('cs', 'behavioral')),
    constraint chk_practice_sessions_status check (status in ('in_progress', 'evaluated', 'failed')),
    constraint chk_practice_sessions_score check (score is null or (score >= 0 and score <= 100))
);

create index idx_practice_sessions_user on practice_sessions (user_id, created_at desc);
create index idx_practice_sessions_user_type on practice_sessions (user_id, question_type, created_at desc);

create table practice_session_tags (
    id                  bigint generated by default as identity primary key,
    practice_session_id bigint      not null references practice_sessions (id) on delete cascade,
    feedback_tag_id     bigint      not null references feedback_tags (id),
    created_at          timestamptz not null default current_timestamp,
    constraint uk_practice_session_tags unique (practice_session_id, feedback_tag_id)
);
