create table users (
    id bigint generated by default as identity primary key,
    email varchar(255),
    display_name varchar(255) not null,
    profile_image_url varchar(1000),
    status varchar(20) not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_users_status check (status in ('active', 'withdrawn'))
);

create unique index ux_users_email_not_null on users (email) where email is not null;
create index idx_users_status on users (status);

create table auth_accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    provider varchar(20) not null,
    provider_user_id varchar(255) not null,
    provider_email varchar(255),
    is_primary boolean not null default false,
    connected_at timestamptz not null default current_timestamp,
    last_login_at timestamptz,
    constraint uk_auth_accounts_provider_user unique (provider, provider_user_id),
    constraint chk_auth_accounts_provider check (provider in ('github', 'google', 'kakao'))
);

create unique index ux_auth_accounts_primary_per_user on auth_accounts (user_id) where is_primary;
create index idx_auth_accounts_user_id on auth_accounts (user_id);

create table github_connections (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    github_user_id bigint not null,
    github_login varchar(255) not null,
    access_scope text,
    sync_status varchar(20) not null,
    connected_at timestamptz not null default current_timestamp,
    last_synced_at timestamptz,
    constraint uk_github_connections_user unique (user_id),
    constraint uk_github_connections_github_user unique (github_user_id),
    constraint chk_github_connections_sync_status check (sync_status in ('pending', 'success', 'failed'))
);

create table github_repositories (
    id bigint generated by default as identity primary key,
    github_connection_id bigint not null references github_connections (id) on delete cascade,
    github_repo_id bigint not null,
    owner_login varchar(255) not null,
    repo_name varchar(255) not null,
    full_name varchar(255) not null,
    html_url varchar(1000) not null,
    visibility varchar(20) not null,
    default_branch varchar(255),
    is_selected boolean not null default false,
    synced_at timestamptz not null default current_timestamp,
    constraint uk_github_repositories_connection_repo unique (github_connection_id, github_repo_id),
    constraint chk_github_repositories_visibility check (visibility in ('public', 'private', 'internal'))
);

create index idx_github_repositories_connection_selected on github_repositories (github_connection_id, is_selected);

create table github_commits (
    id bigint generated by default as identity primary key,
    repository_id bigint not null references github_repositories (id) on delete cascade,
    github_commit_sha varchar(64) not null,
    author_login varchar(255),
    author_name varchar(255),
    author_email varchar(255),
    commit_message text not null,
    is_user_commit boolean not null,
    committed_at timestamptz not null,
    constraint uk_github_commits_repository_sha unique (repository_id, github_commit_sha)
);

create index idx_github_commits_repository_committed_at on github_commits (repository_id, committed_at desc);

create table documents (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    document_type varchar(20) not null,
    original_file_name varchar(255) not null,
    storage_path varchar(1000) not null,
    mime_type varchar(255) not null,
    file_size_bytes bigint not null,
    extract_status varchar(20) not null,
    extracted_text text,
    uploaded_at timestamptz not null default current_timestamp,
    extracted_at timestamptz,
    constraint chk_documents_document_type check (document_type in ('resume', 'award', 'certificate', 'other')),
    constraint chk_documents_extract_status check (extract_status in ('pending', 'success', 'failed'))
);

create index idx_documents_user_type_uploaded_at on documents (user_id, document_type, uploaded_at desc);

create table applications (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    application_title varchar(255),
    company_name varchar(255),
    application_type varchar(100),
    job_role varchar(255) not null,
    status varchar(20) not null,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint chk_applications_status check (status in ('draft', 'ready'))
);

create index idx_applications_user_created_at on applications (user_id, created_at desc);

create table application_source_repositories (
    id bigint generated by default as identity primary key,
    application_id bigint not null references applications (id) on delete cascade,
    repository_id bigint not null references github_repositories (id),
    created_at timestamptz not null default current_timestamp,
    constraint uk_application_source_repositories unique (application_id, repository_id)
);

create table application_source_documents (
    id bigint generated by default as identity primary key,
    application_id bigint not null references applications (id) on delete cascade,
    document_id bigint not null references documents (id),
    created_at timestamptz not null default current_timestamp,
    constraint uk_application_source_documents unique (application_id, document_id)
);

create table application_questions (
    id bigint generated by default as identity primary key,
    application_id bigint not null references applications (id) on delete cascade,
    question_order integer not null,
    question_text text not null,
    generated_answer text,
    edited_answer text,
    tone_option varchar(20),
    length_option varchar(20),
    emphasis_point varchar(255),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint uk_application_questions_order unique (application_id, question_order),
    constraint chk_application_questions_tone_option check (tone_option is null or tone_option in ('formal', 'balanced', 'casual')),
    constraint chk_application_questions_length_option check (length_option is null or length_option in ('short', 'medium', 'long'))
);

create table interview_question_sets (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    application_id bigint not null references applications (id) on delete cascade,
    title varchar(255),
    question_count integer not null,
    difficulty_level varchar(20) not null,
    question_types text[],
    created_at timestamptz not null default current_timestamp,
    constraint chk_interview_question_sets_question_count check (question_count between 1 and 20),
    constraint chk_interview_question_sets_difficulty_level check (difficulty_level in ('easy', 'medium', 'hard'))
);

create table interview_questions (
    id bigint generated by default as identity primary key,
    question_set_id bigint not null references interview_question_sets (id) on delete cascade,
    parent_question_id bigint references interview_questions (id) on delete set null,
    source_application_question_id bigint references application_questions (id) on delete set null,
    question_order integer not null,
    question_type varchar(30) not null,
    difficulty_level varchar(20) not null,
    question_text text not null,
    created_at timestamptz not null default current_timestamp,
    constraint uk_interview_questions_order unique (question_set_id, question_order),
    constraint chk_interview_questions_type check (question_type in ('experience', 'project', 'technical_cs', 'technical_stack', 'behavioral', 'follow_up')),
    constraint chk_interview_questions_difficulty_level check (difficulty_level in ('easy', 'medium', 'hard'))
);

create table interview_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    question_set_id bigint not null references interview_question_sets (id) on delete cascade,
    status varchar(30) not null,
    total_score integer,
    summary_feedback text,
    started_at timestamptz,
    ended_at timestamptz,
    constraint chk_interview_sessions_status check (status in ('ready', 'in_progress', 'paused', 'completed', 'feedback_completed')),
    constraint chk_interview_sessions_total_score check (total_score is null or total_score between 0 and 100)
);

create index idx_interview_sessions_user_status_started_at on interview_sessions (user_id, status, started_at desc);

create table interview_answers (
    id bigint generated by default as identity primary key,
    session_id bigint not null references interview_sessions (id) on delete cascade,
    question_id bigint not null references interview_questions (id) on delete cascade,
    answer_order integer not null,
    answer_text text,
    is_skipped boolean not null,
    score integer,
    evaluation_rationale text,
    created_at timestamptz not null default current_timestamp,
    constraint uk_interview_answers_session_question unique (session_id, question_id),
    constraint chk_interview_answers_score check (score is null or score between 0 and 100),
    constraint chk_interview_answers_answer_text check (is_skipped or nullif(btrim(answer_text), '') is not null)
);

create index idx_interview_answers_session_order on interview_answers (session_id, answer_order);

create table feedback_tags (
    id bigint generated by default as identity primary key,
    tag_name varchar(100) not null,
    tag_category varchar(20) not null,
    description text,
    created_at timestamptz not null default current_timestamp,
    constraint uk_feedback_tags_tag_name unique (tag_name),
    constraint chk_feedback_tags_tag_category check (tag_category in ('content', 'structure', 'evidence', 'communication', 'technical', 'other'))
);

create table interview_answer_tags (
    id bigint generated by default as identity primary key,
    answer_id bigint not null references interview_answers (id) on delete cascade,
    tag_id bigint not null references feedback_tags (id),
    created_at timestamptz not null default current_timestamp,
    constraint uk_interview_answer_tags unique (answer_id, tag_id)
);

insert into feedback_tags (tag_name, tag_category, description)
values
    ('질문 의도 미충족', 'content', '질문에서 요구한 핵심 의도를 직접적으로 충족하지 못한 경우'),
    ('답변 미완', 'content', '답변이 도중에 끊기거나 핵심 결론 없이 끝난 경우'),
    ('구체성 부족', 'content', '경험, 수치, 상황 설명이 추상적으로 머문 경우'),
    ('문제 해결 설명 부족', 'content', '문제 인식부터 해결까지의 흐름이 충분히 드러나지 않은 경우'),
    ('답변 구조 미흡', 'structure', '답변 순서나 구성 때문에 이해가 어려운 경우'),
    ('근거 부족', 'evidence', '주장이나 판단을 뒷받침하는 근거가 부족한 경우'),
    ('기술 정확도 부족', 'technical', '기술 개념이나 사실 설명이 부정확한 경우'),
    ('기술 깊이 부족', 'technical', '기술 선택이나 동작 원리에 대한 깊이가 부족한 경우'),
    ('선택 근거 부족', 'technical', '기술이나 해결 방식을 선택한 이유가 충분히 설명되지 않은 경우'),
    ('표현 명확성 부족', 'communication', '전달 표현이 모호해서 의미가 명확하지 않은 경우');
