-- code_index: 정적 분석 결과 (FQN → 파일 위치 매핑)
-- 소스 원문은 OCI 파일시스템의 클론에서 읽으므로 DB에는 매핑 정보만 저장한다.
create table code_index (
    id                   bigint generated by default as identity primary key,
    github_repository_id bigint not null references github_repositories(id) on delete cascade,
    fqn                  varchar(1000) not null,
    file_path            varchar(2000) not null,
    loc_start            integer,
    loc_end              integer,
    node_type            varchar(20) not null,
    pagerank             double precision,
    authored_by_me       boolean not null default false,
    methods              jsonb,
    analyzed_at          timestamptz not null default current_timestamp,
    constraint uk_code_index_repo_fqn unique (github_repository_id, fqn),
    constraint chk_code_index_node_type check (node_type in ('class', 'function', 'method'))
);

create index idx_code_index_repo_pagerank on code_index (github_repository_id, pagerank desc);
create index idx_code_index_repo_authored on code_index (github_repository_id, authored_by_me);

-- repo_summaries: repo별 AI 생성 요약본 (버전 보존)
create table repo_summaries (
    id                   bigint generated by default as identity primary key,
    user_id              bigint not null references users(id) on delete cascade,
    github_repository_id bigint not null references github_repositories(id) on delete cascade,
    summary_version      integer not null default 1,
    data                 jsonb not null,
    trigger_reason       varchar(30) not null,
    last_synced_commit   varchar(64),
    significance_score   integer,
    generated_at         timestamptz not null default current_timestamp,
    constraint chk_repo_summaries_trigger_reason
        check (trigger_reason in ('new_repo', 'significant_commits', 'manual'))
);

create index idx_repo_summaries_user_repo_version
    on repo_summaries (user_id, github_repository_id, summary_version desc);

-- merged_summaries: 사용자 전체 병합 요약본 (버전 보존)
create table merged_summaries (
    id                bigint generated by default as identity primary key,
    user_id           bigint not null references users(id) on delete cascade,
    merged_version    integer not null default 1,
    included_repo_ids jsonb not null,
    data              jsonb not null,
    merge_strategy    varchar(20) not null,
    generated_at      timestamptz not null default current_timestamp,
    constraint chk_merged_summaries_merge_strategy
        check (merge_strategy in ('json_aggregate', 'llm_rewrite'))
);

create index idx_merged_summaries_user_version
    on merged_summaries (user_id, merged_version desc);

-- github_repositories에 repo_size_kb 추가 (예상 동기화 시간 추정용)
alter table github_repositories
    add column repo_size_kb integer;