create table knowledge_items (
    id           bigint generated by default as identity primary key,
    source_key   varchar(100) not null,
    title        varchar(500) not null,
    content      text         not null,
    file_path    varchar(500) not null,
    content_hash varchar(64)  not null,
    created_at   timestamptz  not null default current_timestamp,
    updated_at   timestamptz  not null default current_timestamp,
    constraint uk_knowledge_items unique (source_key, file_path, title)
);

create table knowledge_tags (
    id       bigint generated by default as identity primary key,
    name     varchar(100) not null,
    category varchar(20)  not null,
    constraint uk_knowledge_tags_name unique (name),
    constraint chk_knowledge_tags_category check (category in ('language', 'topic', 'domain'))
);

create table knowledge_item_tags (
    id                bigint generated by default as identity primary key,
    knowledge_item_id bigint not null references knowledge_items (id) on delete cascade,
    knowledge_tag_id  bigint not null references knowledge_tags (id),
    constraint uk_knowledge_item_tags unique (knowledge_item_id, knowledge_tag_id)
);

create index idx_knowledge_items_source_key on knowledge_items (source_key);
create index idx_knowledge_items_source_path on knowledge_items (source_key, file_path);
