create table interview_session_questions (
    id                         bigint generated by default as identity primary key,
    session_id                 bigint not null references interview_sessions (id) on delete cascade,
    source_question_id         bigint references interview_questions (id) on delete set null,
    parent_session_question_id bigint references interview_session_questions (id) on delete set null,
    question_order             integer not null,
    question_type              varchar(30) not null,
    difficulty_level           varchar(20) not null,
    question_text              text not null,
    created_at                 timestamptz not null default current_timestamp,
    constraint uk_interview_session_questions_order unique (session_id, question_order),
    constraint chk_interview_session_questions_type check (
        question_type in ('experience', 'project', 'technical_cs', 'technical_stack', 'behavioral', 'follow_up')
    ),
    constraint chk_interview_session_questions_difficulty_level check (
        difficulty_level in ('easy', 'medium', 'hard')
    )
);

insert into interview_session_questions (
    session_id,
    source_question_id,
    question_order,
    question_type,
    difficulty_level,
    question_text,
    created_at
)
select session.id,
       question.id,
       question.question_order,
       question.question_type,
       question.difficulty_level,
       question.question_text,
       coalesce(session.started_at, current_timestamp)
from interview_sessions session
         join interview_questions question on question.question_set_id = session.question_set_id;

update interview_session_questions child
set parent_session_question_id = parent.id
from interview_questions source_child
         join interview_questions source_parent on source_parent.id = source_child.parent_question_id
         join interview_session_questions parent
              on parent.source_question_id = source_parent.id
where child.source_question_id = source_child.id
  and parent.session_id = child.session_id;

alter table interview_answers
    add column session_question_id bigint;

update interview_answers answer
set session_question_id = session_question.id
from interview_session_questions session_question
where session_question.session_id = answer.session_id
  and session_question.source_question_id = answer.question_id;

alter table interview_answers
    alter column session_question_id set not null;

alter table interview_answers
    add constraint fk_interview_answers_session_question
        foreign key (session_question_id) references interview_session_questions (id) on delete cascade;

alter table interview_answers
    drop constraint uk_interview_answers_session_question;

alter table interview_answers
    add constraint uk_interview_answers_session_question unique (session_id, session_question_id);

alter table interview_answers
    drop column question_id;
