-- 사용자별 스트릭 추적 (한 행)
create table user_streaks (
    id               bigint generated by default as identity primary key,
    user_id          bigint not null references users (id) on delete cascade,
    current_streak   integer not null default 0,
    longest_streak   integer not null default 0,
    last_active_date date,
    updated_at       timestamptz not null default current_timestamp,
    constraint uk_user_streaks_user unique (user_id),
    constraint chk_user_streaks_streak check (current_streak >= 0 and longest_streak >= 0)
);

-- 히트맵용 일별 활동 요약
create table user_activity_log (
    id             bigint generated by default as identity primary key,
    user_id        bigint not null references users (id) on delete cascade,
    activity_date  date not null,
    activity_count integer not null default 1,
    constraint uk_user_activity_log unique (user_id, activity_date),
    constraint chk_user_activity_log_count check (activity_count >= 1)
);

create index idx_user_activity_log_user_date on user_activity_log (user_id, activity_date desc);
