spring:
  application:
    name: backend
  profiles:
    active: dev

# Actuator 설정 (Prometheus 수집을 위해 필수)
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: spring-app # Prometheus 설정의 job_name과 맞춰주는 것이 좋습니다.