spring:
  config:
    import: optional:file:../.env.dev[.properties]

  datasource:
    # localhost:5432는 로컬 docker-compose에서 뚫어준 포트
    url: jdbc:postgresql://localhost:5432/appdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발 중엔 테이블 자동 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  # github는 redirectionUrl 하나밖에 지원을 안하기 때문에 LOCAL ID,SECRET이 따로 필요
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID_LOCAL:}
            clientSecret: ${GITHUB_CLIENT_SECRET_LOCAL:}
          google:
            clientId: ${GOOGLE_CLIENT_ID:}
            clientSecret: ${GOOGLE_CLIENT_SECRET:}
          kakao:
            clientId: ${KAKAO_CLIENT_ID:}


logging:
  level:
    root: info
    com.back.backend: info

# 개발 환경 JWT 설정
security:
  jwt:
    secret: dev-local-jwt-secret-key-for-debugging-a1b2c3d4e5f6071829384756
    access-ttl-seconds: 900 # 15분
    refresh-ttl-seconds: 86400 # 24시간
  cookie:
    secure: false # HTTP 환경에서 쿠키 전송 가능
