spring:
  config:
    import:
      - optional:file:.env.test[.properties]      # working dir = 프로젝트 루트일 때
      - optional:file:../.env.test[.properties]   # working dir = backend/ 일 때 (CI)

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  flyway:
    enabled: true

  # 팀에서 Redis 사용보류로 결정했으나, Redis 설정을 추가한 브랜치가 머지될 경우
  # PlaceholderResolutionException 방지용 더미값
  data:
    redis:
      host: localhost
      port: 6379

  # github는 redirectionUrl 하나밖에 지원을 안하기 때문에 LOCAL ID,SECRET이 따로 필요
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID_LOCAL:test-github-client-id}
            clientSecret: ${GITHUB_CLIENT_SECRET_LOCAL:test-github-client-secret}
          google:
            clientId: ${GOOGLE_CLIENT_ID:test-google-client-id}
            clientSecret: ${GOOGLE_CLIENT_SECRET:test-google-client-secret}
          kakao:
            clientId: ${KAKAO_CLIENT_ID:test-kakao-client-id}

app:
  storage:
    upload-dir: /tmp/test-uploads #파일업로드 위치

ai:
  gemini:
    api-key: test-key-not-real
    base-url: http://localhost:8089 # MockWebServer 주소
    model: gemini-2.5-flash
    timeout:
      connect: 1s
      read: 5s # 빠른 실패
    retry:
      max-attempts: 0 # 재시도 비활성화

security:
  jwt:
    secret: test-jwt-secret-key-for-integration-tests-9f8e7d6c5b4a3928
    access-ttl-seconds: 60 # 테스트 환경에서는 1분으로 짧게
    refresh-ttl-seconds: 120 # 2분
  cookie:
    secure: false # 테스트 환경
